version: '3'

services:
  nginx:
    image: nginx:alpine
    volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
        - "8080:80"
    depends_on:
        - thor_web
        - potter_web

  # Thor
  thor_db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=thor
      - POSTGRES_USER=thor
      - POSTGRES_DB=thor
  thor_web:
    image: agiliq/multi-tenant-demo
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    depends_on:
      - thor_db
    environment:
      - DATABASE_URL=postgres://thor:thor@thor_db/thor

  thor_migration:
    image: agiliq/multi-tenant-demo
    command: python3 manage.py migrate
    volumes:
      - .:/code
    depends_on:
      - thor_db
    environment:
      - DATABASE_URL=postgres://thor:thor@thor_db/thor

  # Thor
  potter_db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=potter
      - POSTGRES_USER=potter
      - POSTGRES_DB=potter
  potter_web:
    image: agiliq/multi-tenant-demo
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    depends_on:
      - potter_db
    environment:
      - DATABASE_URL=postgres://potter:potter@potter_db/potter

  potter_migration:
    image: agiliq/multi-tenant-demo
    command: python3 manage.py migrate
    volumes:
      - .:/code
    depends_on:
      - thor_db
    environment:
      - DATABASE_URL=postgres://potter:potter@potter_db/potter
